---
title: "Itinérance"
author: "Curbcut"
output: html_document
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

## Itinérance

Il existe des formes d'itinérance à la fois visibles et cachées. L'itinérance cachée est plus difficile à étudier et à quantifier. Le Dénombrement des personnes en situation d’itinérance visible au Québec : Rapport de l’exercice du 11 octobre 2022 fournit une estimation du nombre de personnes vivant en situation d'itinérance visible dans plusieurs régions de la province lors de la nuit du 11 octobre 2022. Le rapport identifie certaines caractéristiques des populations enquêtées et compare les données à celles recueillies en 2018.

Parmi les personnes en situation d’itinérance ayant répondu au sondage dans la région de Laval, la majorité sont des hommes cisgenres (70,1 %). Ceux-ci représentent également la plus grande proportion des individus ayant passé la nuit à l'extérieur, dans un hébergement d'urgence, ou étant dans une situation d'itinérance cachée.123 Cependant, une proportion plus élevée de femmes cisgenres se trouvent dans des organismes mixtes.124 Les personnes issues de la diversité de genres représentent 4 % de la population étudiée.125 En termes d'âge, la plupart des individus ayant passé la nuit à l'extérieur, dans un hébergement d'urgence ou en itinérance cachée ont entre 30 et 49 ans (34,3 %), tandis que les plus jeunes (18-29 ans) sont majoritairement présents dans les ressources de transition et les organismes mixtes.

Définition : Itinérance
« Un processus de désaffiliation sociale et une situation de rupture sociale qui se manifestent par la difficulté pour une personne d’avoir un domicile stable, sécuritaire, adéquat et salubre en raison de la faible disponibilité des logements ou de son incapacité à s’y maintenir et, à la fois, par la difficulté de maintenir des rapports fonctionnels, stables et sécuritaires dans la communauté. L’itinérance s’explique par la combinaison de facteurs sociaux et individuels qui s’inscrivent dans le parcours de vie des hommes et des femmes. »

Environ 4 % des répondants s'identifient comme Autochtones, et 16 % s'identifient comme appartenant à une diversité sexuelle.128 La vaste majorité des personnes interrogées ne sont pas issues de l'immigration (87 %). Ce sont 30 % des individus en situation d'itinérance qui ont passé la nuit avec des connaissances, une proportion plus élevée chez celles en itinérance cachée ou dans une ressource de transition.130 Environ 1 % ont passé la nuit avec un ou plusieurs enfants. Les raisons les plus fréquemment rapportées pour la perte de logement incluent des problèmes de consommation de substances (28 %), des expulsions (26 %), et des conflits interpersonnels (22 %), ces derniers étant plus fréquents à Laval que dans l'ensemble de la province (11 %).

Enfin, les sources de revenus les plus courantes pour les personnes en situation d’itinérance à Laval proviennent des programmes d'aide sociale, suivies par la rémunération liée à un emploi.132 Près de 60 % des personnes interrogées souhaitent recevoir de l'aide pour trouver et garder un logement, tandis que d'autres recherchent des lieux de socialisation, de l'aide à l'emploi ou des services juridiques. Ce sont 17 % des répondants qui n’ont exprimé aucun besoin de services supplémentaires.

L'exercice de dénombrement du 11 octobre 2022 a estimé qu'environ 10 000 personnes étaient en situation d'itinérance visible au Québec dans les 13 régions participantes. À Laval, 169 personnes ont répondu à l’enquête.134 À l’échelle provinciale, 1 335 (13 %) ont passé la nuit dans un lieu extérieur, tandis que 7 481 (74,8 %) ont été hébergées dans des structures comme des hébergements d’urgence, des ressources de transition, des organismes mixtes, ou encore des centres de thérapie et de réadaptation.135 Des tendances similaires ont été observées à Laval, où 22 (10 %) personnes ont passé la nuit dans un lieu extérieur et 106 (62,7 %) ont été hébergées dans des hébergements d’urgence, des ressources de transition, des organismes mixtes, ou des centres de thérapie et de réadaptation.136

Le nombre de personnes en situation d’itinérance le 11 octobre 2022 est probablement sous-estimé. Par rapport à l'exercice de 2018, le dénombrement de 2022 révèle une augmentation marquée de 44 % du nombre de personnes en situation d'itinérance visible dans l’ensemble du Québec, avec des variations régionales allant de 6 % à 268 %.137 À Laval, on constate une hausse de 6%, soit 10 personnes.138 Le rapport cite trois raisons principales expliquant cette augmentation : la pénurie de logements abordables, la pandémie de COVID-19 et l'amélioration de la méthodologie de l'enquête.139

Dans ce contexte, les données du Réseau des organismes et intervenant·e·s en itinérance (ROIIL) concernant le Refuge de Laval pour l’année 2023-2024 mettent en lumière des dynamiques locales importantes. Le Refuge offre principalement un hébergement d’urgence ainsi que des services essentiels, tels que des repas, des douches, des services de lavage et des références pour accompagner les personnes dans leurs démarches personnelles.140 Avec une capacité maintenue à 30 places chaque soir, y compris durant l’été — une période où les services d’hébergement sont souvent réduits —, cette ouverture estivale semble avoir contribué à une diminution des campements recensés par la Ville de Laval, notamment par l’Urgence sociale, par rapport à l’été 2022.

L’achalandage au Refuge a également connu une hausse importante. Un total de 502 nouvelles personnes n’ayant jamais utilisé le volet hébergement ont fait une demande en 2023-2024, soit presque le double par rapport à l’année précédente (297 personnes).142 Cela représente plus d’une nouvelle demande par jour, et en novembre 2023, la 1000e nouvelle personne depuis l’ouverture du Refuge en décembre 2020 a utilisé un lit d’urgence.143 Par ailleurs, entre 2022 et le 31 mars 2024, 800 personnes distinctes ont pu accéder à un hébergement offert par le Refuge d’urgence de Laval.144 Ces données témoignent d’une aggravation de l’itinérance visible à Laval, en phase avec la tendance observée à l’échelle provinciale.

Bien que l'ampleur de l'itinérance visible au Québec semble relativement moindre par rapport à d'autres provinces canadiennes, cette hausse significative entre 2018 et 2024 souligne une aggravation de la situation.