---
title: "Axe 3 - Le soutien aux communautés de proximité"
author: "Curbcut"
output: html_document
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
---

```{r setup3, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Les services de proximité et les équipements collectifs

### Accès aux places en garderie

### Accès aux établissements d'éducation

### Accès aux installations du réseau de la santé et des services sociaux

### Accès aux lieux et édifices municipaux

#### Bibliothèques

#### Centres communautaires

#### Places publiques

#### Centres sportifs

#### Piscines

#### Parcs

#### Lieux culturels non-institutionnels

## La mobilité et le transport

### Accès au réseau d'autobus

#### Densité de trajets disponibles

#### Fréquence du nombre de véhicules accessibles

#### Points de vente pour le transport collectif

### Réseau cyclable

### Système de vélos en libre-service et service d'autoapartage

#### Bixi

#### Communauto

### Bornes de recharge pour véhicules électriques

## Les ressources de soutien et la concertation de quartier